spring.application.name=alivio-web
server.port=8080
spring.thymeleaf.cache=false
server.error.whitelabel.enabled=false
server.error.include-message=never
server.error.include-stacktrace=never
server.servlet.session.tracking-modes=cookie
